# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vikkialets/Documents/Projects/KittySWF

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vikkialets/Documents/Projects/KittySWF

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/vikkialets/Documents/Projects/KittySWF/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Development\" \"Docs\" \"Runtime\" \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vikkialets/Documents/Projects/KittySWF/CMakeFiles /home/vikkialets/Documents/Projects/KittySWF//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vikkialets/Documents/Projects/KittySWF/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/vikkialets/Documents/Projects/KittySWF/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named KittySWF

# Build rule for target.
KittySWF: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 KittySWF
.PHONY : KittySWF

# fast build rule for target.
KittySWF/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittySWF.dir/build.make CMakeFiles/KittySWF.dir/build
.PHONY : KittySWF/fast

#=============================================================================
# Target rules for targets named SDL3-static

# Build rule for target.
SDL3-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL3-static
.PHONY : SDL3-static

# fast build rule for target.
SDL3-static/fast:
	$(MAKE) $(MAKESILENT) -f external/SDL2/CMakeFiles/SDL3-static.dir/build.make external/SDL2/CMakeFiles/SDL3-static.dir/build
.PHONY : SDL3-static/fast

#=============================================================================
# Target rules for targets named SDL3_test

# Build rule for target.
SDL3_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL3_test
.PHONY : SDL3_test

# fast build rule for target.
SDL3_test/fast:
	$(MAKE) $(MAKESILENT) -f external/SDL2/CMakeFiles/SDL3_test.dir/build.make external/SDL2/CMakeFiles/SDL3_test.dir/build
.PHONY : SDL3_test/fast

#=============================================================================
# Target rules for targets named zlib

# Build rule for target.
zlib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zlib
.PHONY : zlib

# fast build rule for target.
zlib/fast:
	$(MAKE) $(MAKESILENT) -f external/zlib/CMakeFiles/zlib.dir/build.make external/zlib/CMakeFiles/zlib.dir/build
.PHONY : zlib/fast

#=============================================================================
# Target rules for targets named zlibstatic

# Build rule for target.
zlibstatic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zlibstatic
.PHONY : zlibstatic

# fast build rule for target.
zlibstatic/fast:
	$(MAKE) $(MAKESILENT) -f external/zlib/CMakeFiles/zlibstatic.dir/build.make external/zlib/CMakeFiles/zlibstatic.dir/build
.PHONY : zlibstatic/fast

#=============================================================================
# Target rules for targets named zlib_example

# Build rule for target.
zlib_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zlib_example
.PHONY : zlib_example

# fast build rule for target.
zlib_example/fast:
	$(MAKE) $(MAKESILENT) -f external/zlib/test/CMakeFiles/zlib_example.dir/build.make external/zlib/test/CMakeFiles/zlib_example.dir/build
.PHONY : zlib_example/fast

#=============================================================================
# Target rules for targets named minigzip

# Build rule for target.
minigzip: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 minigzip
.PHONY : minigzip

# fast build rule for target.
minigzip/fast:
	$(MAKE) $(MAKESILENT) -f external/zlib/test/CMakeFiles/minigzip.dir/build.make external/zlib/test/CMakeFiles/minigzip.dir/build
.PHONY : minigzip/fast

#=============================================================================
# Target rules for targets named zlib_example64

# Build rule for target.
zlib_example64: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zlib_example64
.PHONY : zlib_example64

# fast build rule for target.
zlib_example64/fast:
	$(MAKE) $(MAKESILENT) -f external/zlib/test/CMakeFiles/zlib_example64.dir/build.make external/zlib/test/CMakeFiles/zlib_example64.dir/build
.PHONY : zlib_example64/fast

#=============================================================================
# Target rules for targets named zlib_static_example

# Build rule for target.
zlib_static_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zlib_static_example
.PHONY : zlib_static_example

# fast build rule for target.
zlib_static_example/fast:
	$(MAKE) $(MAKESILENT) -f external/zlib/test/CMakeFiles/zlib_static_example.dir/build.make external/zlib/test/CMakeFiles/zlib_static_example.dir/build
.PHONY : zlib_static_example/fast

#=============================================================================
# Target rules for targets named static_minigzip

# Build rule for target.
static_minigzip: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 static_minigzip
.PHONY : static_minigzip

# fast build rule for target.
static_minigzip/fast:
	$(MAKE) $(MAKESILENT) -f external/zlib/test/CMakeFiles/static_minigzip.dir/build.make external/zlib/test/CMakeFiles/static_minigzip.dir/build
.PHONY : static_minigzip/fast

#=============================================================================
# Target rules for targets named infcover

# Build rule for target.
infcover: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 infcover
.PHONY : infcover

# fast build rule for target.
infcover/fast:
	$(MAKE) $(MAKESILENT) -f external/zlib/test/CMakeFiles/infcover.dir/build.make external/zlib/test/CMakeFiles/infcover.dir/build
.PHONY : infcover/fast

#=============================================================================
# Target rules for targets named zlib_static_example64

# Build rule for target.
zlib_static_example64: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zlib_static_example64
.PHONY : zlib_static_example64

# fast build rule for target.
zlib_static_example64/fast:
	$(MAKE) $(MAKESILENT) -f external/zlib/test/CMakeFiles/zlib_static_example64.dir/build.make external/zlib/test/CMakeFiles/zlib_static_example64.dir/build
.PHONY : zlib_static_example64/fast

external/glad/src/glad.o: external/glad/src/glad.c.o
.PHONY : external/glad/src/glad.o

# target to build an object file
external/glad/src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittySWF.dir/build.make CMakeFiles/KittySWF.dir/external/glad/src/glad.c.o
.PHONY : external/glad/src/glad.c.o

external/glad/src/glad.i: external/glad/src/glad.c.i
.PHONY : external/glad/src/glad.i

# target to preprocess a source file
external/glad/src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittySWF.dir/build.make CMakeFiles/KittySWF.dir/external/glad/src/glad.c.i
.PHONY : external/glad/src/glad.c.i

external/glad/src/glad.s: external/glad/src/glad.c.s
.PHONY : external/glad/src/glad.s

# target to generate assembly for a file
external/glad/src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittySWF.dir/build.make CMakeFiles/KittySWF.dir/external/glad/src/glad.c.s
.PHONY : external/glad/src/glad.c.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittySWF.dir/build.make CMakeFiles/KittySWF.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittySWF.dir/build.make CMakeFiles/KittySWF.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittySWF.dir/build.make CMakeFiles/KittySWF.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... KittySWF"
	@echo "... SDL3-static"
	@echo "... SDL3_test"
	@echo "... infcover"
	@echo "... minigzip"
	@echo "... static_minigzip"
	@echo "... zlib"
	@echo "... zlib_example"
	@echo "... zlib_example64"
	@echo "... zlib_static_example"
	@echo "... zlib_static_example64"
	@echo "... zlibstatic"
	@echo "... external/glad/src/glad.o"
	@echo "... external/glad/src/glad.i"
	@echo "... external/glad/src/glad.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/vikkialets/Documents/Projects/KittySWF/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

